version: '3'
services:
  backend:
    build: 
      context: ./BackPFE-main
      dockerfile: Dockerfile
    volumes:
      - ./BackPFE-main:/usr/src/app
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - database
    environment:
      cors__domains: "http://localhost:3000"
  database:
    image: mongo
    container_name: mongoDatabase
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - database_volume:/var/lib/mongodb/data
  frontend:
    build:
      context: ./FrontPFE-main
      dockerfile: Dockerfile
    volumes:
      - ./FrontPFE-main:/usr/src/app/
    ports:
      - "3001:3001"
    restart: on-failure
    depends_on:
      - backend
    environment:
      cors__domains: "http://localhost:3001"
volumes:
  database_volume:
