version: '3'
services:
  app:
    build: 
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - database
    environment:
      cors__domains: "http://localhost:3000"
  database:
    image: mongo
    container_name: mongoDatabase
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - database_volume:/var/lib/mongodb/data
  #front: 
    #image: frontnew
    #container_name: frontend
    #restart: on-failure
    #ports:
      #- "3001:3001"
volumes:
  database_volume:
